# Generated by Django 3.0.6 on 2020-06-09 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('short_description', models.CharField(max_length=200)),
                ('long_description', models.TextField()),
                ('photo', models.ImageField(blank=True, upload_to='restaurant_images')),
                ('address', models.CharField(max_length=300)),
                ('locality', models.CharField(default=None, max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('contact_number', models.IntegerField()),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('rating', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('northindian', models.BooleanField()),
                ('southindian', models.BooleanField()),
                ('chinese', models.BooleanField()),
                ('continental', models.BooleanField()),
                ('oriental', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('short_description', models.CharField(max_length=200)),
                ('long_description', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to='product_images')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('add_on1', models.CharField(blank=True, default=None, max_length=200)),
                ('add_on2', models.CharField(blank=True, default=None, max_length=200)),
                ('add_on3', models.CharField(blank=True, default=None, max_length=200)),
                ('add_on4', models.CharField(blank=True, default=None, max_length=200)),
                ('add_on5', models.CharField(blank=True, default=None, max_length=200)),
                ('type', models.CharField(choices=[('VEG', 'veg'), ('NON_VEG', 'non_veg')], default='Veg', max_length=20)),
                ('cuisine', models.CharField(choices=[('NorthIndian', 'northindian'), ('SouthIndian', 'southindian'), ('Chinese', 'chinese'), ('Continental', 'continental'), ('Oriental', 'oriental')], default='NothIndian', max_length=20)),
                ('category', models.CharField(choices=[('Breakfast', 'breakfast'), ('Snacks', 'snacks'), ('Lunch/dinner', 'lunch/dinner'), ('Sweet', 'sweet'), ('Dessert', 'dessert')], default='Lunch/Dinner', max_length=30)),
                ('rating', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('restaurant', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='main.Restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=111)),
                ('item_jsons', models.CharField(max_length=6000)),
                ('name', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=200)),
                ('shipping_address', models.CharField(max_length=200)),
                ('billing_address', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('order_time', models.TimeField(auto_now_add=True)),
                ('order_date', models.DateField(auto_now_add=True)),
                ('zip_code', models.CharField(blank=True, max_length=200, null=True)),
                ('total_price', models.CharField(blank=True, max_length=50, null=True)),
                ('order_status', models.CharField(default='pending', max_length=200)),
                ('payment_status', models.CharField(default='', max_length=200)),
                ('payment_mode', models.CharField(default='', max_length=200)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Restaurant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
