# Generated by Django 3.0.6 on 2020-06-11 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_issues'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='live_video',
            field=models.URLField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Breakfast', 'breakfast'), ('Snacks', 'snacks'), ('Lunch/dinner', 'lunch/dinner'), ('Beverages', 'beverages'), ('Dessert/sweet', 'dessert/sweet')], default='Lunch/Dinner', max_length=30),
        ),
    ]
