# Generated by Django 3.0.6 on 2020-06-13 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200613_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='billing_address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='country',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='schedule_date',
            field=models.DateField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='order',
            name='schedule_time',
            field=models.TimeField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='zip_code',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
