# Generated by Django 3.0.6 on 2020-06-14 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200613_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='session_id',
            field=models.CharField(default=None, max_length=300),
        ),
    ]
