# Generated by Django 3.0.6 on 2020-06-14 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_order_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='session_id',
            field=models.CharField(default=None, max_length=300, null=True),
        ),
    ]
