# Generated by Django 3.0.6 on 2020-06-14 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20200614_1925'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
