# Generated by Django 3.0.6 on 2020-06-15 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_booktable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookTable',
        ),
    ]
