# Generated by Django 3.0.6 on 2020-06-15 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_delete_booktable'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookTable',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=30)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_phone_number', models.IntegerField()),
                ('date', models.DateField(blank=True, default=None)),
                ('time', models.TimeField(blank=True, default=None)),
                ('number_of_people', models.IntegerField()),
                ('message', models.CharField(blank=True, max_length=400)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Restaurant')),
            ],
        ),
    ]
