# Generated by Django 3.0.6 on 2020-06-15 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_booktable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktable',
            name='number_of_people',
            field=models.IntegerField(default=0),
        ),
    ]
