# Generated by Django 3.0.6 on 2020-06-15 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
